---
# Prechecks for Drover services

- name: Check API port availability
  ansible.builtin.wait_for:
    host: "{{ api_interface_address | default('127.0.0.1') }}"
    port: "{{ drover_api_port }}"
    state: stopped
    timeout: 5
  when:
    - inventory_hostname in groups['drover-api'] | default([])
    - drover_services['drover-api'].enabled | bool
