---
galaxy_info:
  role_name: drover
  author: openstack-afterglow
  description: Drover K3s Kubernetes provisioning service deployment role for kolla-ansible
  min_ansible_version: "2.14"

dependencies: []
