---
- name: Pull | Pull Drover images
  become: true
  community.docker.docker_image:
    name: "{{ item.value.image }}"
    source: pull
    force_source: true
  no_log: true
  loop: "{{ drover_services | dict2items }}"
  when:
    - inventory_hostname in groups['drover']
    - item.value.enabled | bool
    - not (drover_source_mode | default(false) | bool)
